site_name: OceanEye Documentation
site_url: https://oceaneye.github.io
theme:
  name: material
  palette:
    scheme: slate
    primary: blue
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Creating your first project: getting-started/first-project.md
  - Documentation:
    - Project Structure: documentation/project.md
    - Edit Media: documentation/edit-media.md
    - Model Training: documentation/model-training.md

