site_name: OceanEye Documentation
site_url: https://oceaneye.github.io
theme:
  name: material
  features:
    - navigation.footer
  palette:
    scheme: slate
    primary: blue
    accent: deep orange
extra:
  generator: false
  copyright: Copyright &copy; 2025 SOLIDS Lab, UVic
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OceanEye-Project/OceanEye-QT
    - icon: material/web
      link: https://solidslab.ca/
repo_url: https://github.com/OceanEye-Project/OceanEye-QT
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Creating your first project: getting-started/first-project.md
  - Documentation:
    - Project Structure: documentation/project.md
    - Edit Media: documentation/edit-media.md
    - Model Training: documentation/model-training.md

