name: Build and Deploy

on: 
  push: 
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v4
        
      - name: Install deps
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build MkDocs
        run: mkdocs build --clean

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./site